project_id = "uzulqexlgavggcyizabf"

[functions.expert-chat]
verify_jwt = false

[functions.save-lead]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.upload-document]
verify_jwt = false
